base: 'https://www.sl-creations.net/'
baseVariants:
  -
    base: 'https://kwible.ddev.site:8443'
    condition: 'getenv("IS_DDEV_PROJECT") == "true"'
  -
    base: 'https://sl-creations.net'
    condition: 'applicationContext == "Production"'
disableStaticFileCache: false
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=14#31'
languages:
  -
    title: French
    enabled: true
    languageId: 0
    base: /
    typo3Language: fr
    locale: fr_FR
    iso-639-1: fr
    navigationTitle: French
    hreflang: fr-fr
    direction: ltr
    flag: fr
matomoWidgetsActiveWidgets: 'actionsPerDay,actionsPerMonth,annotations,createAnnotation,bounceRate,browserPlugins,browsers,campaigns,contentNames,contentPieces,countries,javaScriptErrors,linkMatomo,osFamilies,pagesNotFound,siteSearchKeywords,siteSearchNoResultKeywords,visitsPerDay,visitsPerMonth'
matomoWidgetsIdSite: 1
matomoWidgetsPagesNotFoundTemplate: '404/URL = {path}/From = {referrer}'
matomoWidgetsTitle: 'SL Créations'
matomoWidgetsTokenAuth: '%env(MATOMO_TOKEN)%'
matomoWidgetsUrl: '%env(MATOMO_URL)%'
rootPageId: 2
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow:"
websiteTitle: 'SL Créations'
imports:
  -
    resource: 'EXT:theme_package/Configuration/Route/routeEnhancers.yaml'
