base: 'https://www.thomas-beck.fr'
baseVariants:
  -
    base: 'https://www.thomas-beck.fr'
    condition: 'applicationContext == "Production"'
  -
    base: 'https://typo3.ddev.site:44334/thomasbeck'
    condition: 'getenv("IS_DDEV_PROJECT") == "true"'
languages:
  -
    title: French
    enabled: true
    locale: fr_FR.utf8
    hreflang: fr-FR
    base: /
    websiteTitle: ''
    navigationTitle: French
    flag: fr
    languageId: 0
matomoWidgetsActiveWidgets: ''
matomoWidgetsIdSite: ''
matomoWidgetsPagesNotFoundTemplate: '404/URL = {path}/From = {referrer}'
matomoWidgetsTitle: ''
matomoWidgetsTokenAuth: ''
matomoWidgetsUrl: ''
rootPageId: 85
websiteTitle: 'Thomas Beck Intégrateur web expert en accessibilité'
