name: tbhck/blue-block
typeName: tbhck_blueblock
group: slcreation
prefixFields: true
prefixType: full
basics:
    - TYPO3/Appearance
fields:
  -
    identifier: header
    useExistingField: true
  -
    identifier: bodytext
    useExistingField: true
    enableRichtext: true
  -
    identifier: image
    type: Image
    useExistingField: true

  - identifier: Couleur
    type: Select
    renderType: selectSingle
    items:
      - label: 'Piscine'
        value: blue
      - label: 'Etanchéité'
        value: red
      - label: 'Equipement'
        value: gray
      - label: 'Aménagement'
        value: brown
