name: thbck/squares
typeName: thbck_squares
group: educcanine
prefixFields: true
prefixType: full
fields:
  -
    identifier: header
    useExistingField: true
  -
    identifier: squares
    type: Collection
    labelField: title
    fields:
      - identifier: title
        type: Text
      - identifier: Icone
        type: File
        maxitems: 1
      - identifier: bodytext
        type: Textarea
        useExistingField: true
        enableRichtext: true
      - identifier: Couleur
        type: Select
        renderType: selectSingle
        items:
          - label: 'Rose'
            value: pink
          - label: 'Violet'
            value: purple
          - label: 'Orange'
            value: orange